package fail.tiger.jellytiger.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF8F4E00)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDCC2)
val md_theme_light_onPrimaryContainer = Color(0xFF2E1500)
val md_theme_light_secondary = Color(0xFF954A00)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDCC6)
val md_theme_light_onSecondaryContainer = Color(0xFF301400)
val md_theme_light_tertiary = Color(0xFF5B6237)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE0E7B1)
val md_theme_light_onTertiaryContainer = Color(0xFF191E00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF201B17)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF201B17)
val md_theme_light_surfaceVariant = Color(0xFFF3DFD1)
val md_theme_light_onSurfaceVariant = Color(0xFF51443B)
val md_theme_light_outline = Color(0xFF847469)
val md_theme_light_inverseOnSurface = Color(0xFFFAEEE8)
val md_theme_light_inverseSurface = Color(0xFF352F2B)
val md_theme_light_inversePrimary = Color(0xFFFFB77B)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF8F4E00)
val md_theme_light_outlineVariant = Color(0xFFD6C3B6)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB77B)
val md_theme_dark_onPrimary = Color(0xFF4C2700)
val md_theme_dark_primaryContainer = Color(0xFF6D3A00)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDCC2)
val md_theme_dark_secondary = Color(0xFFFFB785)
val md_theme_dark_onSecondary = Color(0xFF502500)
val md_theme_dark_secondaryContainer = Color(0xFF713700)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDCC6)
val md_theme_dark_tertiary = Color(0xFFC4CB97)
val md_theme_dark_onTertiary = Color(0xFF2D330D)
val md_theme_dark_tertiaryContainer = Color(0xFF444A22)
val md_theme_dark_onTertiaryContainer = Color(0xFFE0E7B1)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF201B17)
val md_theme_dark_onBackground = Color(0xFFECE0DA)
val md_theme_dark_surface = Color(0xFF201B17)
val md_theme_dark_onSurface = Color(0xFFECE0DA)
val md_theme_dark_surfaceVariant = Color(0xFF51443B)
val md_theme_dark_onSurfaceVariant = Color(0xFFD6C3B6)
val md_theme_dark_outline = Color(0xFF9E8E82)
val md_theme_dark_inverseOnSurface = Color(0xFF201B17)
val md_theme_dark_inverseSurface = Color(0xFFECE0DA)
val md_theme_dark_inversePrimary = Color(0xFF8F4E00)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB77B)
val md_theme_dark_outlineVariant = Color(0xFF51443B)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF80552F)